api_platform:
    title: "API de mon projet"
    version: "1.0.0"
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
